### PR TITLE
Added script for checking diff of generated code 

### PR DESCRIPTION
**Pull request by evalsocket**
# TL;DR
- Added check for verify go-gen, it will fail if contributor forget to generate code

## Type
- [ ] Bug Fix
- [x] Feature
- [ ] Plugin

## Are all requirements met?

- [x] Code completed
- [x] Smoke tested
- [x] Unit tests added
- [x] Code documentation added
- [ ] Any pending items have an associated Issue

## Complete description
_How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
https://github.com/flyteorg/flyte/issues/1872

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

### CODE REVIEW

**Comment by katrogan** [comment]
@evalsocket i think it's related to https://github.com/flyteorg/flytepropeller/pull/341

**Comment by evalsocket** [comment]
@katrogan because i run `make generate`, it added some change in generated files. unit test are working fine in master but after `make generate`, It is failing

**Comment by katrogan** [comment]
@evalsocket yes I understand, I pulled your branch and ran unit tests

**Comment by evalsocket** [comment]
@katrogan tests are failing because of new changes, `go generate ./...` generate mocks that is failing, 

I am not sure why we have diff when we run `go generate ./...`

**Comment by evalsocket** [comment]
@katrogan did you find anything ?

**Review by katrogan — APPROVED** [review]

**Pull request merged**
