### PR TITLE
Fix: register remaining tasks without default

### PR DESCRIPTION
**Pull request by regadas**
Fixes https://github.com/flyteorg/flyte/issues/1049

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [x] Smoke tested
 - [x] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Tracking Issue
https://github.com/flyteorg/flyte/issues/1049

### CODE REVIEW

**Comment by regadas** [comment]
Hi @EngHabu @kumare3 👋 

Currently affected by this, if you could take a look it would be very much appreciated 🙏 Thank you!

**Review by katrogan — APPROVED** [review]
looks good, but i think the unit test you added passes as is, no?

**Review by kumare3 — APPROVED** [review]

**Comment by kumare3** [comment]
@regadas please merge

**Comment by regadas** [comment]
Hello!

@katrogan without the change test will fail like:
```
--- FAIL: Test_task_Setup (0.06s)
    --- FAIL: Test_task_Setup/partial-default-task-types (0.01s)
        handler_test.go:255: 
            	Error Trace:	handler_test.go:255
            	Error:      	Should be true
            	Test:       	Test_task_Setup/partial-default-task-types
            	Messages:   	plugin k8s not found
FAIL
```

Thank you all for the reviews!

**Pull request merged**
